name: ru_family
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase and other dependencies
  change_app_package_name: ^1.5.0
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  firebase_auth: ^6.0.2
  firebase_ui_auth: ^3.0.0
  google_sign_in: ^7.1.1
  firebase_storage: ^13.0.1
  connectivity_plus: ^7.0.0
  shared_preferences: ^2.5.3
  workmanager: ^0.9.0+3
  flutter_cache_manager: ^3.4.1
  permission_handler: ^12.0.1
  url_launcher: ^6.3.2
  photo_view: ^0.15.0
  cached_network_image: ^3.4.1
  share_plus: ^12.0.1
  gallery_saver_plus: ^3.2.9
  shimmer: ^3.0.0
  pdf: ^3.11.3
  printing: ^5.14.2
  google_fonts: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png

  fonts:
    - family: CustomBangla1
      fonts:
        - asset: assets/fonts/1.ttf
    - family: CustomBangla2
      fonts:
        - asset: assets/fonts/2.ttf
    - family: CustomBangla3
      fonts:
        - asset: assets/fonts/3.ttf
