// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2qh1ga_D7fAqh4PAfjEHfQYhWeVIBcX4',
    appId: '1:745123500157:web:99d909a09b17f39ebf6114',
    messagingSenderId: '745123500157',
    projectId: 'ornate-justice-394207',
    authDomain: 'ornate-justice-394207.firebaseapp.com',
    storageBucket: 'ornate-justice-394207.firebasestorage.app',
    measurementId: 'G-BL3F9QTSLM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpeLdVi-UcSl26N0AQG7NuHQbDETmyyKc',
    appId: '1:745123500157:android:f4c17e82990046bebf6114',
    messagingSenderId: '745123500157',
    projectId: 'ornate-justice-394207',
    storageBucket: 'ornate-justice-394207.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCblx5Fw8HF6mjRWtFr1pSXLDXpwPgGHa4',
    appId: '1:745123500157:ios:a5226cd22fee62b8bf6114',
    messagingSenderId: '745123500157',
    projectId: 'ornate-justice-394207',
    storageBucket: 'ornate-justice-394207.firebasestorage.app',
    iosBundleId: 'com.ru.family',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2qh1ga_D7fAqh4PAfjEHfQYhWeVIBcX4',
    appId: '1:745123500157:web:e747d0256bddde7bbf6114',
    messagingSenderId: '745123500157',
    projectId: 'ornate-justice-394207',
    authDomain: 'ornate-justice-394207.firebaseapp.com',
    storageBucket: 'ornate-justice-394207.firebasestorage.app',
    measurementId: 'G-TJS0KBDJCB',
  );
}
